In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

c

# ========== Data ==========

In [2]:
data = pd.read_csv('dataset.csv')

In [3]:
data

x1  x2  y
0   0   1  1
1   1   0  1
2  -1   0  0
3   0  -1  0

In [4]:
X = data[['x1', 'x2']]

In [5]:
y = data['y']

# ========== Model ==========

In [6]:
clf = SVC(kernel='linear')
clf.fit(X, y)

SVC(kernel='linear')

In [7]:
clf.intercept_

array([-0.])

In [8]:
clf.coef_

array([[1., 1.]])

# ========== Prediction ==========

In [9]:
X = pd.read_csv('incoming_data.csv')

In [10]:
X

x1   x2
0  0.0  1.5
1  1.5  0.0
2 -1.5  0.0
3  0.0 -1.5

In [11]:
clf.predict(X)

array([1, 1, 0, 0])