In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
saved_model = pickle.load(open('banana_model.pickle', 'rb'))

In [3]:
reg = saved_model[0]
ordinal_encoder = saved_model[1]
one_hot_encoder = saved_model[2]
scaler = saved_model[3]
feature_name = saved_model[4]
numerical_feature = saved_model[5]
ordinal_feature = saved_model[6]
nominal_feature = saved_model[7]

In [4]:
feature_name

['SOIL TYPE', 'REGION', 'TEMPERATURE', 'WEATHER CONDITION']

In [5]:
SOIL_TYPE = 'HUMID'
REGION = 'DESERT'
TEMPERATURE = '30-40'
WEATHER_CONDITION = 'NORMAL'

In [6]:
incoming_data = pd.DataFrame(np.array([[SOIL_TYPE, REGION, TEMPERATURE, WEATHER_CONDITION]]), 
                             columns=feature_name)

incoming_data

SOIL TYPE  REGION TEMPERATURE WEATHER CONDITION
0     HUMID  DESERT       30-40            NORMAL

In [7]:
print('numerical_feature :', numerical_feature)
print('ordinal_feature :', ordinal_feature)
print('nominal_feature :', nominal_feature)

numerical_feature : []
ordinal_feature : ['SOIL TYPE', 'REGION', 'TEMPERATURE']
nominal_feature : ['WEATHER CONDITION']


### Ordinal Encoding

In [8]:
incoming_data[ordinal_feature] = ordinal_encoder.transform(incoming_data[ordinal_feature])

### One Hot Encoding

In [9]:
one_hot_feature = one_hot_encoder.categories_[0]

incoming_data[one_hot_feature] = one_hot_encoder.transform(incoming_data[nominal_feature])
incoming_data.drop(nominal_feature, axis=1, inplace=True)

incoming_data_scaled = scaler.transform(incoming_data)

incoming_data_scaled

array([[0.5       , 0.        , 0.66666667, 1.        , 0.        ,
        0.        , 0.        ]])

In [10]:
incoming_data_scaled

array([[0.5       , 0.        , 0.66666667, 1.        , 0.        ,
        0.        , 0.        ]])

### Prediction

In [11]:
predicted_target = reg.predict(incoming_data_scaled)

In [12]:
predicted_target

array([8.80050247])